compiler = { path = "/home/ed/Code/thesis-spade-lang/spade/" }

[board]
name = "ecpix-5"
pin_file = "ecpix5.lpf"
config_file = "openocd-ecpix5.cfg"

[synthesis]
command = "synth_ecp5"
top = "main"
extra_verilog = [
    "src/top.v"
]

[pnr]
architecture = "ecp5"
device = "LFE5U-85F"
pin_file = "ulx3s_v20.lpf"
package = "CABGA381"
allow_unconstrained=true
